# Primitive trampoline table generator (Emscripten)
#
#     cmake -DSOURCE=<file.c> -DTABLE=<X>_exports -DOUTPUT=<X>_primitives.c
#           [-DMARKERS=ON] -P genPrimitiveTable.cmake
#     cmake -DSOURCE=<interpreter.c> -DMARKERS=ON -P genPrimitiveTable.cmake
#
# The interpreter calls every named primitive through void (*)(void), but
# most generated and checked-in primitives are declared to return sqInt, and
# a WebAssembly call_indirect traps unless the callee has exactly the type of
# the call.  This script reads the one Slang exports table of SOURCE (its rows
# are indented by a tab),
#
#     void* <X>_exports[][3] = {
#         {(void*)_m, "name\000\ddd", (void*)name},
#         ...
#         {NULL, NULL, NULL}
#     };
#
# and writes OUTPUT, a translation unit that #includes SOURCE unchanged and
# adds
#
#     static void w_name(void) { name(); }
#     void *<X>_primitives[][3] = { ... };
#
# with one trampoline for every row that carries an accessor depth (the
# primitives) and otherwise the same rows.  Named-primitive lookups use
# <X>_primitives, and the typed lookups (ioLoadFunctionFrom and the module
# life cycle) keep using <X>_exports.  Each trampoline is compiled against the
# real prototype, so a wrong arity is a compile error, and a static assertion
# checks that no row was lost.  A line of the table that is neither a Slang
# row nor a preprocessor line stops the build.
#
# MARKERS=ON also requires the Emscripten hooks of the Slang sources in
# SOURCE, the generated interpreter: without them the VM would still build,
# but it would never return to the host, and it would place its memory where
# the native VM does.  Without TABLE and OUTPUT only that check is made.
#
# OUTPUT is rewritten only when its contents change.

cmake_minimum_required(VERSION 3.10)

if(NOT SOURCE)
    message(FATAL_ERROR "genPrimitiveTable.cmake: SOURCE is not set")
endif()
get_filename_component(SOURCE "${SOURCE}" ABSOLUTE)
file(READ "${SOURCE}" source)
# Every line of interest starts after a newline, even the first one.
string(REPLACE "\r\n" "\n" source "\n${source}")

if(MARKERS)
    set(missing "")
    string(FIND "${source}" "\n#define pollHeartbeat() PHARO_POLL_HEARTBEAT()\n" found)
    if(found EQUAL -1)
        string(APPEND missing ", the pollHeartbeat() #define")
    endif()
    string(FIND "${source}" "pollHeartbeat();" found)
    if(found EQUAL -1)
        string(APPEND missing ", the pollHeartbeat() calls")
    endif()
    string(FIND "${source}" "__EMSCRIPTEN__" found)
    if(found EQUAL -1)
        string(APPEND missing ", the __EMSCRIPTEN__ memory map")
    endif()
    if(NOT missing STREQUAL "")
        string(SUBSTRING "${missing}" 2 -1 missing)
        message(FATAL_ERROR "${SOURCE} lacks the Emscripten hooks of the "
            "Slang sources (${missing}): it was generated by a VMMaker image "
            "older than this tree.  Rerun `make wasm`, which refreshes the "
            "VMMaker image and regenerates the sources, or pass generated "
            "sources that carry the Emscripten hooks.")
    endif()
    if(NOT TABLE AND NOT OUTPUT)
        return()
    endif()
endif()

if(NOT TABLE MATCHES "^[A-Za-z_][A-Za-z0-9_]*_exports$")
    message(FATAL_ERROR "genPrimitiveTable.cmake: TABLE must name a <X>_exports table, not '${TABLE}'")
endif()
if(NOT OUTPUT)
    message(FATAL_ERROR "genPrimitiveTable.cmake: OUTPUT is not set")
endif()
string(REGEX REPLACE "_exports$" "_primitives" primitives "${TABLE}")

set(header "\nvoid* ${TABLE}[][3] = {\n")
string(FIND "${source}" "${header}" start)
if(start EQUAL -1)
    message(FATAL_ERROR "${SOURCE}: no '${TABLE}' table")
endif()
string(LENGTH "${header}" length)
math(EXPR start "${start} + ${length}")
string(SUBSTRING "${source}" ${start} -1 rest)
string(FIND "${rest}" "\n};\n" end)
if(end EQUAL -1)
    message(FATAL_ERROR "${SOURCE}: the '${TABLE}' table does not end")
endif()
string(SUBSTRING "${rest}" 0 ${end} table)

# The lines are taken one by one rather than as a CMake list, whose ';' and
# '[' handling could merge or split them.
set(trampolines "")
set(rows "")
string(APPEND table "\n")
while(NOT table STREQUAL "")
    string(FIND "${table}" "\n" eol)
    string(SUBSTRING "${table}" 0 ${eol} line)
    math(EXPR eol "${eol} + 1")
    string(SUBSTRING "${table}" ${eol} -1 table)

    if(line MATCHES "^#")
        string(APPEND trampolines "${line}\n")
        string(APPEND rows "${line}\n")
    elseif(line MATCHES "^\t{\\(void\\*\\)_m, \"([A-Za-z_][A-Za-z0-9_]*)(\\\\000\\\\[0-7][0-7][0-7])\", \\(void\\*\\)([A-Za-z_][A-Za-z0-9_]*)},$")
        set(name "${CMAKE_MATCH_1}")
        set(depth "${CMAKE_MATCH_2}")
        set(function "${CMAKE_MATCH_3}")
        string(APPEND trampolines "static void w_${function}(void) { ${function}(); }\n")
        string(APPEND rows "\t{(void*)_m, \"${name}${depth}\", (void*)w_${function}},\n")
    elseif(line MATCHES "^\t{\\(void\\*\\)_m, \"[A-Za-z_][A-Za-z0-9_]*\", \\(void\\*\\)[A-Za-z_][A-Za-z0-9_]*},$"
            OR line STREQUAL "\t{NULL, NULL, NULL}")
        string(APPEND rows "${line}\n")
    else()
        message(FATAL_ERROR "${SOURCE}: unexpected line in the '${TABLE}' table: '${line}'")
    endif()
endwhile()

file(WRITE "${OUTPUT}.tmp"
"/* Generated by cmake/emscripten/genPrimitiveTable.cmake from
   ${SOURCE}.
   Do not edit. */

#include \"${SOURCE}\"

/* The interpreter calls named primitives through void (*)(void), and a
   WebAssembly indirect call traps unless the callee has exactly that type:
   every row with an accessor depth gets a trampoline of that type. */
${trampolines}
void *${primitives}[][3] = {
${rows}};

_Static_assert(sizeof(${primitives}) == sizeof(${TABLE}),
	\"${primitives} lost rows of ${TABLE}\");
")
configure_file("${OUTPUT}.tmp" "${OUTPUT}" COPYONLY)
file(REMOVE "${OUTPUT}.tmp")
