# Table of the support primitives of the FFI (Emscripten)
#
#     cmake -DOUTPUT=<vmsupport_exports.c> -DSOURCES=<a.c;b.c;...> -P genSupportTable.cmake
#
# The primitives of src/ffi have no module: natively the image finds them
# with a global dlsym (and their accessor depth through the variable
# <name>AccessorDepth).  There is no dlsym in the Emscripten VM, so this
# script reads the definitions
#
#     Primitive(name) { ... }
#     PrimitiveWithDepth(name, N) { ... }
#
# of SOURCES (include/pharovm/macros.h: void name(void), and
# signed char nameAccessorDepth = N) and writes OUTPUT, which defines the
# module-less table vmsupport_exports, in the format of Slang's tables:
#
#     {(void*)_m, "name\000\ddd", (void*)name}
#
# with the accessor depth in the byte after the name (octal ddd, -1 as 377).
# The primitives are void (*)(void) already, so the table serves both the
# named-primitive lookups and ioLoadFunctionFrom.  OUTPUT is rewritten only
# when its contents change.

cmake_minimum_required(VERSION 3.10)

if(NOT OUTPUT OR NOT SOURCES)
    message(FATAL_ERROR "genSupportTable.cmake: OUTPUT and SOURCES must be set")
endif()

set(names "")
foreach(source IN LISTS SOURCES)
    file(STRINGS "${source}" lines REGEX "^[ \t]*Primitive(WithDepth)?[ \t]*\\(")
    foreach(line IN LISTS lines)
        if(line MATCHES "^[ \t]*PrimitiveWithDepth[ \t]*\\([ \t]*([A-Za-z_][A-Za-z0-9_]*)[ \t]*,[ \t]*(-?[0-9]+)[ \t]*\\)")
            set(name "${CMAKE_MATCH_1}")
            set(depth "${CMAKE_MATCH_2}")
        elseif(line MATCHES "^[ \t]*Primitive[ \t]*\\([ \t]*([A-Za-z_][A-Za-z0-9_]*)[ \t]*\\)")
            set(name "${CMAKE_MATCH_1}")
            set(depth 0)
        else()
            message(FATAL_ERROR "${source}: cannot read the primitive definition '${line}'")
        endif()
        if(depth LESS -1 OR depth GREATER 127)
            message(FATAL_ERROR "${source}: accessor depth ${depth} of ${name} is out of range")
        endif()
        if(depth LESS 0)
            math(EXPR depth "256 + ${depth}")
        endif()
        # three octal digits
        math(EXPR d0 "${depth} % 8")
        math(EXPR d1 "(${depth} / 8) % 8")
        math(EXPR d2 "${depth} / 64")
        list(FIND names "${name}" found)
        if(NOT found EQUAL -1)
            message(FATAL_ERROR "${source}: primitive ${name} is defined twice")
        endif()
        list(APPEND names "${name}")
        set(row_${name} "\t{(void*)_m, \"${name}\\000\\${d2}${d1}${d0}\", (void*)${name}},\n")
    endforeach()
endforeach()
list(SORT names)

set(declarations "")
set(rows "")
foreach(name IN LISTS names)
    string(APPEND declarations "extern void ${name}(void);\n")
    string(APPEND rows "${row_${name}}")
endforeach()

file(WRITE "${OUTPUT}.tmp"
"/* Generated by cmake/emscripten/genSupportTable.cmake from the Primitive
   definitions of src/ffi.  Do not edit. */

#include <stddef.h>

${declarations}
static char _m[] = \"\";
void *vmsupport_exports[][3] = {
${rows}\t{NULL, NULL, NULL}
};
")
configure_file("${OUTPUT}.tmp" "${OUTPUT}" COPYONLY)
file(REMOVE "${OUTPUT}.tmp")
