# Builtin primitive tables of the Emscripten VM
#
# The Emscripten VM links every plugin in, and looks their functions up in the
# tables of include/pharovm/sqNamedPrims.h.  WebAssembly checks the type of
# every indirect call, and the interpreter calls named primitives through
# void (*)(void), so each exports table gets a companion table of void(void)
# trampolines, generated at build time by genPrimitiveTable.cmake.
#
# This support file defines the following functions
#
#     pharo_wasm_primitive_table(<outVar> SOURCE <file> TABLE <X>_exports [MARKERS])
#         Adds a custom command generating ${CMAKE_BINARY_DIR}/wasm/prims/<X>_primitives.c,
#         a translation unit that #includes <file> and defines <X>_primitives,
#         and sets <outVar> to its path.  The generated file is compiled
#         instead of <file>.  MARKERS, for the interpreter, also requires the
#         Emscripten hooks of the Slang sources.
#
#     pharo_wasm_write_builtin_header(<header> TABLES <X>...)
#         Writes <header>, which defines pluginExports (vm_exports,
#         os_exports, vmsupport_exports, <X>_exports...) and pluginPrimitives
#         (vm_primitives, os_exports, vmsupport_exports, <X>_primitives...).
#         sqNamedPrims.h includes it when PHARO_BUILTIN_PLUGINS_HEADER names it.
#         os_exports (empty) and vmsupport_exports (void primitives only) need
#         no trampolines, and serve both lookups.
#
#     pharo_wasm_check_markers(<file>)
#         Stops the configuration when the generated interpreter <file> lacks
#         the Emscripten hooks of the Slang sources.

set(PHARO_WASM_PRIMITIVE_TABLE_GENERATOR "${CMAKE_CURRENT_LIST_DIR}/genPrimitiveTable.cmake")

function(pharo_wasm_primitive_table outVar)
    cmake_parse_arguments(ARG "MARKERS" "SOURCE;TABLE" "" ${ARGN})
    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "pharo_wasm_primitive_table: unexpected arguments ${ARG_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT ARG_SOURCE)
        message(FATAL_ERROR "pharo_wasm_primitive_table: no SOURCE")
    endif()
    if(NOT ARG_TABLE MATCHES "^[A-Za-z_][A-Za-z0-9_]*_exports$")
        message(FATAL_ERROR "pharo_wasm_primitive_table: TABLE must name a <X>_exports table, not '${ARG_TABLE}'")
    endif()
    get_filename_component(source "${ARG_SOURCE}" ABSOLUTE)
    string(REGEX REPLACE "_exports$" "_primitives" name "${ARG_TABLE}")
    set(output "${CMAKE_BINARY_DIR}/wasm/prims/${name}.c")
    set(markers "")
    if(ARG_MARKERS)
        set(markers "-DMARKERS=ON")
    endif()

    # The generator rewrites the output only when it changes; the touch keeps
    # it newer than its dependencies, so the command does not rerun.
    add_custom_command(
        OUTPUT "${output}"
        COMMAND ${CMAKE_COMMAND} "-DSOURCE=${source}" "-DTABLE=${ARG_TABLE}"
                "-DOUTPUT=${output}" ${markers} -P "${PHARO_WASM_PRIMITIVE_TABLE_GENERATOR}"
        COMMAND ${CMAKE_COMMAND} -E touch_nocreate "${output}"
        DEPENDS "${source}" "${PHARO_WASM_PRIMITIVE_TABLE_GENERATOR}"
        COMMENT "Generating the primitive trampolines of ${ARG_TABLE}"
        VERBATIM)
    set(${outVar} "${output}" PARENT_SCOPE)
endfunction()

function(pharo_wasm_write_builtin_header header)
    cmake_parse_arguments(ARG "" "" "TABLES" ${ARGN})
    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "pharo_wasm_write_builtin_header: unexpected arguments ${ARG_UNPARSED_ARGUMENTS}")
    endif()
    set(declarations "extern sqExport vm_exports[];\nextern sqExport vm_primitives[];\n")
    string(APPEND declarations "extern sqExport os_exports[];\nextern sqExport vmsupport_exports[];\n")
    set(exports "\tvm_exports,\n\tos_exports,\n\tvmsupport_exports,\n")
    set(primitives "\tvm_primitives,\n\tos_exports,\n\tvmsupport_exports,\n")
    foreach(table IN LISTS ARG_TABLES)
        if(NOT table MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
            message(FATAL_ERROR "pharo_wasm_write_builtin_header: '${table}' is not the <X> of a <X>_exports table")
        endif()
        string(APPEND declarations "extern sqExport ${table}_exports[];\nextern sqExport ${table}_primitives[];\n")
        string(APPEND exports "\t${table}_exports,\n")
        string(APPEND primitives "\t${table}_primitives,\n")
    endforeach()

    set(text
"/* Generated by cmake/emscripten/primitiveTables.cmake.  Do not edit.
   Named primitives are looked up in pluginPrimitives, whose primitives have
   the type void (*)(void) the interpreter calls them through, and every other
   function in pluginExports. */

${declarations}
sqExport *pluginExports[] = {
${exports}\tNULL
};

sqExport *pluginPrimitives[] = {
${primitives}\tNULL
};
")
    set(old "")
    if(EXISTS "${header}")
        file(READ "${header}" old)
    endif()
    if(NOT old STREQUAL text)
        file(WRITE "${header}" "${text}")
    endif()
endfunction()

function(pharo_wasm_check_markers source)
    if(ARGN)
        message(FATAL_ERROR "pharo_wasm_check_markers: unexpected arguments ${ARGN}")
    endif()
    get_filename_component(source "${source}" ABSOLUTE)
    execute_process(
        COMMAND ${CMAKE_COMMAND} "-DSOURCE=${source}" -DMARKERS=ON -P "${PHARO_WASM_PRIMITIVE_TABLE_GENERATOR}"
        RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "The generated interpreter ${source} cannot be built for Emscripten (see above).")
    endif()
endfunction()
