[package]
name = "pharo-vm-plugin-macros"
description = "Attribute macros for pharo-vm-plugin. Not useful on its own; use pharo-vm-plugin."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
