//! Access to the interpreter proxy and to VM-core exports, from code that is
//! not itself a primitive.
//!
//! The C support functions (`sqFileOpen`, `dir_Lookup`, ...) reach the
//! interpreter through the global `interpreterProxy` the generated plugin
//! shim assigns in `setInterpreter`. Our `setInterpreter` is generated by
//! `pharo_plugin!`, which stores the table in
//! `pharo_vm_plugin::__private::INTERP`; reading it back here is the one
//! deliberate use of that non-stable module, confined to this file.
//!
//! The C plugin also calls functions the VM core exports directly
//! (`getVMGMTOffset` from heartbeat.c, `aioEnable`/`aioHandle`/`aioDisable`
//! from aio.c) and resolves them at link time. A Rust cdylib cannot, so they
//! are obtained at runtime through the proxy's `ioLoadFunctionFrom(name, "")`
//! -- the empty module name searches the VM itself, the same way the C
//! UnixOSProcessPlugin resolves `ioGetEnvVec` -- and cached.

use core::sync::atomic::{AtomicI32, Ordering};
use std::ffi::c_void;
use std::sync::OnceLock;

use pharo_vm_plugin::proxy::{sqInt, VirtualMachine};

/// The proxy table, or `None` before `setInterpreter` ran (which includes
/// unit tests, where there is no VM at all).
pub(crate) fn proxy() -> Option<&'static VirtualMachine> {
    let vt = pharo_vm_plugin::__private::INTERP.load(Ordering::Acquire);
    if vt.is_null() {
        None
    } else {
        // SAFETY: setInterpreter only ever stores the VM's own
        // process-lifetime proxy table, never mutated after hand-over.
        Some(unsafe { &*vt })
    }
}

/// Calls `interpreterProxy->success(false)`: records a primitive failure.
///
/// The C support functions do this on every failure path. Answers 0 so
/// callers can `return fail()` where the C wrote
/// `return interpreterProxy->success(false)`.
pub(crate) fn fail() -> sqInt {
    if let Some(p) = proxy() {
        if let Some(f) = p.success {
            // SAFETY: proxy entry supplied by the VM; signature fixed by the
            // published proxy ABI.
            unsafe { f(0) };
        }
    }
    0
}

/// Calls `interpreterProxy->success(true)`, mirroring the C's
/// `return interpreterProxy->success(true)` (which does not clear an earlier
/// failure -- success is ANDed in).
pub(crate) fn succeed() -> sqInt {
    if let Some(p) = proxy() {
        if let Some(f) = p.success {
            // SAFETY: as in `fail`.
            return unsafe { f(1) };
        }
    }
    1
}

/// The session identifier: `int thisSession` in the C.
///
/// Zero until `sqFileInit` runs; zero is never a valid session, which is how
/// records left over from a previous image run are detected. Truncated to
/// `int` exactly as the C's assignment from `sqInt` does.
static THIS_SESSION: AtomicI32 = AtomicI32::new(0);

pub(crate) fn this_session() -> libc::c_int {
    THIS_SESSION.load(Ordering::Relaxed)
}

pub(crate) fn set_this_session_from_vm() {
    if let Some(p) = proxy() {
        if let Some(f) = p.getThisSessionID {
            // SAFETY: as in `fail`.
            let id = unsafe { f() };
            THIS_SESSION.store(id as libc::c_int, Ordering::Relaxed);
        }
    }
}

/// Copies a Smalltalk file name into a NUL-terminated C path, resolving
/// aliases when asked -- `ioFilenamefromStringofLengthresolveAliases` in the
/// proxy, which is what every C path in this plugin used.
///
/// Without a proxy (unit tests) it falls back to a plain bounded copy, which
/// is what the VM's unix implementation does anyway when alias resolution is
/// off.
///
/// Answers `None` where the C treated the copy as failed: name too long for
/// the buffer, or a non-zero return with `resolve_aliases` set.
pub(crate) fn resolve_filename(name: &[u8], resolve_aliases: bool) -> Option<Vec<u8>> {
    // The C copied into `char cFileName[PATH_MAX]` and failed on
    // `size >= sizeof(cFileName)`.
    const PATH_MAX: usize = 4096;
    if name.len() >= PATH_MAX {
        return None;
    }
    let mut buf = vec![0u8; PATH_MAX];
    match proxy().and_then(|p| p.ioFilenamefromStringofLengthresolveAliases) {
        Some(f) => {
            // SAFETY: `buf` holds PATH_MAX writable bytes and `name` is
            // readable for its length; the VM's implementation NUL-terminates
            // within the buffer for lengths < PATH_MAX.
            let status = unsafe {
                f(
                    buf.as_mut_ptr().cast(),
                    name.as_ptr() as *mut libc::c_char,
                    name.len() as sqInt,
                    sqInt::from(resolve_aliases),
                )
            };
            // The C only checks the return value on the resolving paths
            // (open, openNew); delete and rename ignore it.
            if resolve_aliases && status != 0 {
                return None;
            }
        }
        None => {
            buf[..name.len()].copy_from_slice(name);
            buf[name.len()] = 0;
        }
    }
    Some(buf)
}

type GmtOffsetFn = unsafe extern "C" fn() -> libc::c_longlong;
type AioEnableFn = unsafe extern "C" fn(fd: sqInt, client_data: *mut c_void, flags: libc::c_int);
type AioHandler = unsafe extern "C" fn(fd: sqInt, client_data: *mut c_void, flag: libc::c_int);
type AioHandleFn = unsafe extern "C" fn(fd: sqInt, handler: AioHandler, mask: libc::c_int);
type AioDisableFn = unsafe extern "C" fn(fd: sqInt);

/// Looks a function up in the VM executable itself via the proxy.
fn vm_function(name: &'static [u8]) -> *mut c_void {
    debug_assert!(name.ends_with(b"\0"));
    match proxy().and_then(|p| p.ioLoadFunctionFrom) {
        // SAFETY: both strings are NUL-terminated; an empty module name means
        // "search the VM executable" (see sqUnixExternalPrims.c).
        Some(f) => unsafe { f(name.as_ptr() as *mut libc::c_char, c"".as_ptr().cast_mut()) },
        None => core::ptr::null_mut(),
    }
}

/// `getVMGMTOffset()` from the VM core (heartbeat.c), or 0 when unavailable
/// (unit tests; a core built without the export). The C linked it directly.
pub(crate) fn vm_gmt_offset() -> libc::c_longlong {
    static CACHE: OnceLock<Option<GmtOffsetFn>> = OnceLock::new();
    let f = CACHE.get_or_init(|| {
        let p = vm_function(b"getVMGMTOffset\0");
        if p.is_null() {
            None
        } else {
            // SAFETY: the symbol is the core's `long long getVMGMTOffset(void)`.
            Some(unsafe { core::mem::transmute::<*mut c_void, GmtOffsetFn>(p) })
        }
    });
    match f {
        // SAFETY: resolved from the VM's own export table.
        Some(f) => unsafe { f() },
        None => 0,
    }
}

/// The VM core's async-io registry, resolved as a trio because
/// `waitForDataonSemaphoreIndex` needs all three or none.
pub(crate) struct Aio {
    pub enable: AioEnableFn,
    pub handle: AioHandleFn,
    pub disable: AioDisableFn,
}

pub(crate) fn aio() -> Option<&'static Aio> {
    static CACHE: OnceLock<Option<Aio>> = OnceLock::new();
    CACHE
        .get_or_init(|| {
            let enable = vm_function(b"aioEnable\0");
            let handle = vm_function(b"aioHandle\0");
            let disable = vm_function(b"aioDisable\0");
            if enable.is_null() || handle.is_null() || disable.is_null() {
                return None;
            }
            // SAFETY: the symbols are the core's aio.c exports, whose
            // signatures are fixed by include/pharovm/common/aio.h.
            unsafe {
                Some(Aio {
                    enable: core::mem::transmute::<*mut c_void, AioEnableFn>(enable),
                    handle: core::mem::transmute::<*mut c_void, AioHandleFn>(handle),
                    disable: core::mem::transmute::<*mut c_void, AioDisableFn>(disable),
                })
            }
        })
        .as_ref()
}

/// `interpreterProxy->signalSemaphoreWithIndex`, for the aio callback.
pub(crate) fn signal_semaphore_with_index(index: sqInt) {
    if let Some(p) = proxy() {
        if let Some(f) = p.signalSemaphoreWithIndex {
            // SAFETY: as in `fail`.
            unsafe { f(index) };
        }
    }
}
