name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - pharo-10
jobs:
  ubuntu:
    env:
      CC: clang
      CXX: clang++
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pharo-vm
      - run: sudo apt install build-essential clang
      - run: bash pharo-vm/scripts/github-ubuntu.sh