name: learn-github-actions
on:
  push:
    branches:
      - pharo-10
jobs:
  ubuntu:
    env:
      CC: clang
      CXX: clang++
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pharo-vm
      - run: sudo apt install build-essential clang libpango1.0-dev libpangocairo-1.0-0 libpoppler-dev
      - run: bash pharo-vm/scripts/github-ubuntu.sh
      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create r${{github.run_number}} pharo-vm-build/build/dist/pharo-vm-ubuntu.zip