name: Continuous integration
on:
  push:
    branches:
      - pharo-10
jobs:

  images:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pharo-vm
      - name: Install dependencies
        run: sudo apt install curl
      - name: Fetch images
        run: bash pharo-vm/scripts/github-fetch-images.sh
      - name: Upload release assets
        run: |
          cd pharo-vm
          gh release create r${{github.run_number}}
          gh release upload r${{github.run_number}} ../fresh-images/90/Pharo64-90.zip
          gh release upload r${{github.run_number}} ../fresh-images/100/Pharo64-100.zip
          gh release upload r${{github.run_number}} ../fresh-images/110/Pharo64-110.zip
          gh release upload r${{github.run_number}} ../fresh-images/120/Pharo64-120.zip
          gh release upload r${{github.run_number}} ../fresh-images/130/Pharo64-130.zip
          gh release upload r${{github.run_number}} ../fresh-images/alpha/Pharo64-alpha.zip

  ubuntu:
    needs: images
    env:
      CC: clang
      CXX: clang++
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pharo-vm
      - name: Install dependencies
        run: sudo apt install build-essential clang curl libbz2-dev libexpat1-dev libffi-dev libfreetype-dev libpixman-1-dev libpng-dev libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev libpango1.0-dev libpangocairo-1.0-0 libpangoft2-1.0-0 libpangoxft-1.0-0 libgit2-dev libffi-dev libffindex0-dev libtty-dev libpoppler-dev libpoppler-glib-dev libgit2-glib-1.0-dev libssh2-1-dev openssl libgdk-pixbuf-2.0-dev libgtk-4-dev
      - name: Build Pharo VM
        run: bash pharo-vm/scripts/github-ubuntu.sh
      - name: Upload release assets
        run: |
          cd pharo-vm
          gh release upload r${{github.run_number}} ../pharo-vm-build/build/dist/pharo-vm-ubuntu.zip
          gh release upload r${{github.run_number}} ../booklet-image/Pharo130-booklet.zip
  
  windows:
    needs: images
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          location: D:\
          update: true
          msystem: UCRT64
          install: >-
            git
            zip
            unzip
            autoconf2.72
            automake1.16
            mingw-w64-ucrt-x86_64-curl
            mingw-w64-ucrt-x86_64-lua
            mingw-w64-ucrt-x86_64-wget
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-clang
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-cairo
            mingw-w64-ucrt-x86_64-pango
            mingw-w64-ucrt-x86_64-poppler
            mingw-w64-ucrt-x86_64-libgit2
            mingw-w64-ucrt-x86_64-libssh2
            mingw-w64-ucrt-x86_64-libtool
            mingw-w64-ucrt-x86_64-tree-sitter
            mingw-w64-ucrt-x86_64-nodejs
            mingw-w64-ucrt-x86_64-gdk-pixbuf2
            mingw-w64-ucrt-x86_64-gtk4
      - uses: actions/checkout@v4
        with:
          path: pharo-vm
      - name: Build Pharo VM
        run: bash pharo-vm/scripts/github-windows.sh
      - name: Upload release assets
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd pharo-vm
          gh release upload r${{github.run_number}} ../pharo-vm-build/build/dist/pharo-vm-windows.zip
          gh release upload r${{github.run_number}} ../msys2-fetcher.lua/test/pharo-goodies.zip
  
  macos:
    needs: images
    env:
      CC: clang
      CXX: clang++
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pharo-vm
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"  
      - name: Install Dependencies  
        run: |
          brew install wget curl cmake bzip2 expat libffi freetype pixman libpng sdl2 sdl2_gfx sdl2_image sdl2_mixer sdl2_net sdl2_ttf pango cairo libgit2  libgit2-glib poppler libssh2 gtk4 gdk-pixbuf node tree-sitter
          sudo ln -s /usr/local/Cellar/tree-sitter/0.22.6/bin/tree-sitter /usr/local/bin/tree-sitter
          sudo update_dyld_shared_cache
      - name: Build Pharo VM
        run: bash pharo-vm/scripts/github-macos.sh
      - name: Upload release assets
        run: |
          cd pharo-vm
          gh release upload r${{github.run_number}} ../pharo-vm-build/build/dist/pharo-vm-macos.zip

  