name: Continuous integration
on:
  push:
    branches:
      - pharo-10
jobs:
  ubuntu:
    env:
      CC: clang
      CXX: clang++
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pharo-vm
      - name: Install dependencies
        run: sudo apt install build-essential clang libpango1.0-dev libpangocairo-1.0-0 libpoppler-dev curl
      - name: Fetch images
        run: bash pharo-vm/scripts/github-fetch-images.sh
      - name: Build Pharo VM
        run: bash pharo-vm/scripts/github-ubuntu.sh
      - name: Upload release assets
        run: |
          cd pharo-vm
          gh release create r${{github.run_number}} ../fresh-images/fresh-images.zip
          gh release upload r${{github.run_number}} ../pharo-vm-build/build/dist/pharo-vm-ubuntu.zip
  
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          location: D:\
          update: true
          msystem: UCRT64
          install: >-
            git
            zip
            unzip
            autoconf2.72
            automake1.16
            mingw-w64-ucrt-x86_64-curl
            mingw-w64-ucrt-x86_64-lua
            mingw-w64-ucrt-x86_64-wget
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-clang
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-cairo
            mingw-w64-ucrt-x86_64-pango
            mingw-w64-ucrt-x86_64-poppler
            mingw-w64-ucrt-x86_64-libgit2
            mingw-w64-ucrt-x86_64-libssh2
            mingw-w64-ucrt-x86_64-libtool
      - uses: actions/checkout@v4
        with:
          path: pharo-vm
      - name: Build Pharo VM
        run: bash pharo-vm/scripts/github-windows.sh
      - name: Upload release assets
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd pharo-vm
          gh release upload r${{github.run_number}} ../pharo-vm-build/build/dist/pharo-vm-windows.zip
          gh release upload r${{github.run_number}} ../msys2-fetcher.lua/test/pharo-goodies.zip